export const surveyConstants = {
    ADD_SURVEY: 'ADD_SURVEY',

    SURVEYS_REQUEST_INIT: 'SURVEYS_REQUEST_INIT',
    SURVEYS_REQUEST_SUCCESS: 'SURVEYS_REQUEST_SUCCESS',
    SURVEYS_REQUEST_ERROR: 'SURVEYS_REQUEST_ERROR',
};
